name: CMake Build and Test

on:
  push:
    branches:
      - project1-tests
  pull_request:
    branches:
      - project1-tests

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake-action@v2
        with:
          cmake-version: '3.21.2'

      - name: Build with CMake
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Run tests
        run: |
          cmake --build build --target test
