name: CMake Build and Test

on:
  push:
    branches:
      - project1-tests
  pull_request:
    branches:
      - project1-tests

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            generator: "Visual Studio 17 2022"
          - os: ubuntu-latest
            generator: "Unix Makefiles"
          - os: macos-latest
            generator: "Unix Makefiles"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.25.x'

      - name: Configure CMake
        run: cmake -S . -B build -G "${{ matrix.generator }}"

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        working-directory: build
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            ctest -C Release -V
          else
            ctest -V
          fi
        shell: bash