name: Cross-Platform CMake Build and Test

on:
  push:
    branches:
      - project1-tests
  pull_request:
    branches:
      - project1-tests

jobs:
  build_and_test:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_type: Release
          - os: windows-latest
            build_type: Release
          - os: macos-latest
            build_type: Release

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install cmake -y

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build project
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Run tests
        run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.build_type }}
